---

- name: Deploy passenger service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/enmasse.yml
    - group_vars/tools.yml

  tasks:
    - import_role:
        name: openshift_passenger_service
      vars:
        ocp_project: "{{ project_services }}"
        ocp_project_display_name: "{{ project_services_name }}"
        ocp_project_desc: "{{ project_services_desc }}"
        resources_dir: "{{ ocp_dir }}/passenger-service"
        playbook_work_dir: "{{ work_dir }}/passenger-service"